# Generated by Django 4.0.4 on 2022-08-25 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=60, null=True)),
                ('Date_Created', models.DateTimeField(auto_now_add=True, null=True)),
                ('Profile_Img', models.ImageField(blank=True, default='Default-Pic.png', null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
