# Generated by Django 4.0.4 on 2022-08-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_Img',
            field=models.ImageField(blank=True, default='Default-Pic.png', null=True, upload_to='Profile_pic'),
        ),
    ]
