# Generated by Django 4.0.4 on 2022-08-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='Fullname',
        ),
    ]
