# Generated by Django 4.0.4 on 2022-08-29 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_shipmentform_other'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentform',
            name='InvoiceOUM',
            field=models.CharField(choices=[('Each', 'Each'), ('Carton', 'Carton'), ('Pail', 'Pail'), ('Piece', 'Piece'), ('Pair', 'Pair'), ('Bottle', 'Bottle')], max_length=70, null=True),
        ),
    ]
