# Generated by Django 4.0.4 on 2022-08-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_shipmentform_invoiceoum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentform',
            name='BillOfLanding',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='CustomDeclarationNumber',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='DateOfIncident',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='DetailOfDiscrepancy',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='Forwarder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='InvoiceNumber',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='InvoiceOUM',
            field=models.CharField(blank=True, choices=[('Each', 'Each'), ('Carton', 'Carton'), ('Pail', 'Pail'), ('Piece', 'Piece'), ('Pair', 'Pair'), ('Bottle', 'Bottle')], max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='InvoiceQuantity',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='ModeOfTranSportation',
            field=models.CharField(blank=True, choices=[('Air', 'Air'), ('Truck', 'Truck'), ('Ocean', 'Ocean')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='PartNumber',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='PickTicket',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='ProcessingTime',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='ShipperCountry',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='ShipperName',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='ShippingDocument',
            field=models.FileField(blank=True, null=True, upload_to='ShippingDocument'),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='Status',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='SubmitBy',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='SupplierNAme',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='TotalPackage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='TypeOfDiscrepancy',
            field=models.CharField(blank=True, choices=[('Shortage', 'Shortage Quantity'), ('Over', 'Over Quantity'), ('Wrong', 'Wrong Parts'), ('PO', 'PO Problem')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='UnitPrice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
