# Generated by Django 4.0.4 on 2022-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_actioncause'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentform',
            name='Area',
            field=models.CharField(blank=True, choices=[('local', 'local'), ('Oversea', 'Oversea')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentform',
            name='TypeOfDiscrepancy',
            field=models.CharField(blank=True, choices=[('Shortage Quantity', 'Shortage Quantity'), ('Over Quantity', 'Over Quantity'), ('Wrong Parts', 'Wrong Parts'), ('PO Problem', 'PO Problem')], max_length=40, null=True),
        ),
    ]
