# Generated by Django 4.0.4 on 2022-08-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_shipmentform_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncause',
            name='Action',
            field=models.CharField(blank=True, choices=[('Replace or Return Shipment', 'Replace or Return Shipment'), ('Correct Invoice', 'Correct Invoice'), ('Credit Note', 'Credit Note')], max_length=30, null=True),
        ),
    ]
