# Generated by Django 4.0.4 on 2022-08-30 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_actioncause_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncause',
            name='Transaction_Number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ActionCause', to='App.shipmentform'),
        ),
    ]
