# Generated by Django 4.0.4 on 2022-09-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_actioncause_transaction_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentform',
            name='PartDescription',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
